# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-west-2"



  default_tags {
    tags = { "kb:env" : "prod", "kb:managed-by" : "terraform", "kb:name" : "terraform-aws-baseline" }
  }
}

provider "aws" {
  alias  = "management"
  region = "eu-west-2"

  default_tags {
    tags = { "kb:env" : "prod", "kb:managed-by" : "terraform", "kb:name" : "terraform-aws-baseline" }
  }
}


provider "aws" {
  alias  = "management-eu-west-2"
  region = "eu-west-2"

  default_tags {
    tags = { "kb:env" : "prod", "kb:managed-by" : "terraform", "kb:name" : "terraform-aws-baseline" }
  }
}

provider "aws" {
  alias  = "management-us-east-1"
  region = "us-east-1"

  default_tags {
    tags = { "kb:env" : "prod", "kb:managed-by" : "terraform", "kb:name" : "terraform-aws-baseline" }
  }
}
