name: Dependabot auto-merge

on:
  pull_request:

jobs:
  autoupdate:
    uses: kieranbrown/github-actions/.github/workflows/dependabot-auto-merge.yaml@v1
    permissions:
      contents: write
      pull-requests: write
