name: Digger Workflow

on:
  issue_comment:
    types: [created]
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, closed ]
  schedule: ## 5am every week on Saturday
    - cron: "0 5 * * 6"

jobs:
  digger-job:
    uses: kieranbrown/github-actions/.github/workflows/digger-workflow.yaml@v1
    secrets: inherit
    permissions:
      actions: write       # required for plan persistence
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
